#pragma config(Sensor, in1,    ,               sensorSONAR_cm, int1)
#pragma config(Sensor, in2,    ,               sensorSONAR_cm, int2)
#pragma config(Sensor, in3,    ,               sensorDigitalOut)
#pragma config(Sensor, in4,    ,               sensorDigitalOut)
#pragma config(Sensor, in5,    ,               sensorDigitalOut)
#pragma config(Sensor, in13,   ,               sensorDigitalOut)
#pragma config(Sensor, in14,   ,               sensorDigitalOut)
#pragma config(Sensor, in15,   ,               sensorDigitalIn)
#pragma config(Sensor, in16,   ,               sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef ASEC_INCLUDE
#define ASEC_INCLUDE

#include "Main.h"
#include "Interrupts.h"
#include "Movement.h"
#include "Stability.h"

#endif

#define INTERRUPT_MAX 32765
#define SCONT_OFF SensorValue[in16]

task main()
{
	SensorValue[in5] = 1;
	char InterruptValue = 0;
	int InterruptCount = 0;

	bVexAutonomousMode = false;
	InitializeInterrupts();
	InitializeMovement();
	InitializeStability();

	while(!SCONT_OFF) {
		// If either of the Channel 5 buttons is pressed, allow full manual
		// control.
		if(vexRT[Ch5]) {
			ExecuteMovementScheme();
			continue;
		}

		// Check for and handle Interrupts
		// Each Interrupt function should handle the Interrupt itself, and return
		// 1 if it detected an Interrupt, or 0 if it did not.
		// InterruptValue will be 1 if ANY Interrupt function detects an Interrupt.
		InterruptValue = SControllerInterrupt() |
						UltrasonicInterrupt() |
						StabilityInterrupt();
		if(InterruptValue) {
			InterruptValue = 0;
			InterruptCount++;
			continue;
		} else if (InterruptCount > 0)	{
			// No Interrupt occured; decrement the counter towards 0
			InterruptCount--;
		}

		// If we are stuck in an Interrupt condition for too long, stop the
		// motors and shut down
		if(InterruptCount > INTERRUPT_MAX) {
			StopMotors();
			break;
		}

		//Control System
		ExecuteMovementScheme();
		ExcecuteStabilityScheme();

		// FOR TESTING ONLY
		// Send a signal to the secondary controller if Ch6 is active.
		if(vexRT[Ch6])
			SensorValue[in13] = 1;
		else
			SensorValue[in13] = 0;

	}
}

#include "Interrupts.c"
#include "Movement.c"
#include "Stability.c"
