#pragma config(Sensor, in1,    ,               sensorReflection)
#pragma config(Sensor, in2,    ,               sensorTouch)
#pragma config(Sensor, in3,    ,               sensorTouch)
#pragma config(Sensor, in4,    ,               sensorTouch)
#pragma config(Sensor, in5,    ,               sensorDigitalOut)
#pragma config(Sensor, in6,    ,               sensorDigitalOut)
#pragma config(Sensor, in7,    ,               sensorDigitalOut)
#pragma config(Sensor, in8,    ,               sensorDigitalOut)
#pragma config(Sensor, in9,    ,               sensorDigitalOut)
#pragma config(Sensor, in10,   ,               sensorDigitalOut)
#pragma config(Sensor, in13,   ,               sensorDigitalIn)
#pragma config(Sensor, in14,   ,               sensorDigitalIn)
#pragma config(Sensor, in15,   ,               sensorDigitalOut)
#pragma config(Sensor, in16,   ,               sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef ASEC_INCLUDE
#define ASEC_INCLUDE

#include "Main.h"
#include "Interrupts.h"

#endif

task main()
{
	int test;
	bVexAutonomousMode = false;
	SensorValue[in16] = 1;

	while (true) {
		// Check whether the RC controller is connected and signal the main controller.
		char rxint = RxInterrupt();
		char lint = LiftInterrupt();
		test = SensorValue[in14];
		if(rxint || lint || !SensorValue[in14]) {
			SensorValue[in5] = 0;
			SensorValue[in15] = 1;
		} else {
			SensorValue[in5] = 1;
			SensorValue[in15] = 0;
		}

		// FOR TESTING ONLY
		// If the sensor value on in13 is 0, Ch6 is active.
		// Set an IO port
		if(SensorValue[in13] == 0)
			SensorValue[in5] = 1;
	}

	SensorValue[in6] = 1;
	SensorValue[in7] = 1;
	SensorValue[in8] = 1;
	SensorValue[in9] = 1;
	SensorValue[in10] = 1;
	SensorValue[in16] = 0;
}

#include "Interrupts.c"
